#!/usr/bin/env  python

#
# this code is generated by Claude Sonnet 5.5
#

#
#  Client Sample Code
#  0.0Vから3.3Vまで変動する電圧を HiveMQ パブリックブローカーにpublish するサンプルスクリプト
#  MQTT Dashboard デモ用のPublish Client
#
#   broker: broker.hivemq.com
#   topic:  org00/sensor/rp01/vr
#   message:  {"voltage" : <value>} 
#              <value> := 0.0 - 3.3
#
import json
import math
import time

import paho.mqtt.client as mqtt

BROKER = 'broker.hivemq.com'
PORT = 1883                      # TLSを使うなら 8883 + client.tls_set()
TOPIC = 'org00/sensor/rp01/vr'
MAX_VOL = 3.3


def on_connect(client, userdata, flags, reason_code, properties):
    print(f'Connected: {reason_code}')


def on_disconnect(client, userdata, disconnect_flags, reason_code, properties):
    if reason_code.is_failure:
        print(f'Unexpected disconnection: {reason_code}')


def on_publish(client, userdata, mid, reason_code, properties):
    print(f'publish: {mid}')


def main():
    client = mqtt.Client(mqtt.CallbackAPIVersion.VERSION2)
    client.on_connect = on_connect
    client.on_disconnect = on_disconnect
    client.on_publish = on_publish

    client.connect(BROKER, PORT, 60)
    client.loop_start()

    try:
        t0 = time.time()
        while True:
            v = MAX_VOL/2 + MAX_VOL/2 * math.sin(2 * math.pi * (time.time() - t0) / 20)
            payload = json.dumps({'voltage': round(v, 3)})
            client.publish(TOPIC, payload)
            time.sleep(1)
    except KeyboardInterrupt:
        pass
    finally:
        client.loop_stop()
        client.disconnect()


main()
#
# this code is generated by Claude Sonnet 5.5
#
