#!/usr/bin/env  python

# This code is generated by Claude(Sonnet 5.5)
# Prompt:
#  センサーデータを視覚化したいと思います。まずはVRによるアナログ電圧をグラフ化します。
#  NiceGUIにおいて、2 カラムにして、左側にはタコメータのように円と針で、0V - 3.3Vまで、
#  タコメータ風の針がふれる、右側には、時系列で表示される折れ線グラフとして、
#  値が入るたびにタコメータの針が動き、それと共に折れ線グラフの値が追加されるような
#  niceGUIを使ったコード書けますか？
#  情報はMQTT Brokerから取ってくるものとします。

"""VR(可変抵抗)のアナログ電圧を MQTT で受け取り、NiceGUI で可視化する。
左: タコメータ風ゲージ (0 - 3.3V)
右: 時系列折れ線グラフ

ライブラリインストール: 
     pip install nicegui paho-mqtt   (paho-mqtt は 2.x が前提)
"""

import json
import math
import threading
import time
from collections import deque

import paho.mqtt.client as mqtt
from nicegui import app, ui

# ---- 設定 ---------------------------------------------------------------
BROKER_HOST = 'broker.hivemq.com'
#BROKER_PORT = 8883
BROKER_PORT = 1883
TOPIC = 'org00/sensor/rp01/vr'    # payload: "1.65" または {"voltage": 1.65}
V_MIN, V_MAX = 0.0, 3.3
MAX_POINTS = 300             # 折れ線に保持する点数(2〜3Hzなら約2分)
# -------------------------------------------------------------------------

class Store:
    """MQTTスレッドとUI側で共有するデータ置き場(スレッドセーフ)。"""

    def __init__(self) -> None:
        self._lock = threading.Lock()
        self._points: deque = deque(maxlen=MAX_POINTS)
        self.seq = 0          # 新着ごとに +1。UI側はこれで更新有無を判定
        self.latest = 0.0

    def add(self, v: float) -> None:
        with self._lock:
            self._points.append([int(time.time() * 1000), v])
            self.latest = v
            self.seq += 1

    def snapshot(self):
        with self._lock:
            return self.seq, self.latest, list(self._points)


store = Store()

def parse_voltage(payload: bytes):
    text = payload.decode(errors='ignore').strip()
    try:
        v = float(text)
    except ValueError:
        try:
            v = float(json.loads(text)['voltage'])
        except (ValueError, KeyError, TypeError):
            return None
    if not math.isfinite(v):
        return None
    return max(V_MIN, min(V_MAX, v))


# ---- MQTT ---------------------------------------------------------------
mqtt_client = mqtt.Client(mqtt.CallbackAPIVersion.VERSION2)


def on_connect(client, userdata, flags, reason_code, properties):
    print(f'MQTT connected: {reason_code}')
    client.subscribe(TOPIC)   # 再接続時にも購読し直す


def on_message(client, userdata, msg):
    print('received message')
    v = parse_voltage(msg.payload)
    if v is not None:
        store.add(v)


mqtt_client.on_connect = on_connect
mqtt_client.on_message = on_message


def start_mqtt() -> None:
    mqtt_client.connect_async(BROKER_HOST, BROKER_PORT)
    mqtt_client.loop_start()  # 別スレッドで受信・自動再接続


def stop_mqtt() -> None:
    mqtt_client.loop_stop()
    mqtt_client.disconnect()


app.on_startup(start_mqtt)
app.on_shutdown(stop_mqtt)


# ---- UI -----------------------------------------------------------------
@ui.page('/')
def index():
    seq, latest, points = store.snapshot()

    ui.label('VR アナログ電圧モニタ').classes('text-h5')

    with ui.grid(columns=2).classes('w-full gap-4'):
        # 左: ゲージ
        with ui.card().classes('w-full'):
            gauge = ui.echart({
                'animationDurationUpdate': 300,
                'animationEasingUpdate': 'cubicOut',
                'series': [{
                    'type': 'gauge',
                    'min': V_MIN,
                    'max': V_MAX,
                    'startAngle': 225,
                    'endAngle': -45,
                    'splitNumber': 11,       # 0.3V刻み
                    'radius': '90%',
                    'axisLine': {'lineStyle': {
                        'width': 16,
                        'color': [[0.6, '#4caf50'], [0.85, '#ffb300'], [1.0, '#e53935']],
                    }},
                    'pointer': {'length': '70%', 'width': 6},
                    'anchor': {'show': True, 'size': 14},
                    'axisLabel': {'distance': 24, 'fontSize': 12},
                    'detail': {
                        'valueAnimation': True,
                        'formatter': '{value} V',
                        'fontSize': 30,
                        'offsetCenter': [0, '65%'],
                    },
                    'data': [{'value': round(latest, 2)}],
                }],
            }).classes('w-full h-96')

        # 右: 時系列折れ線
        with ui.card().classes('w-full'):
            line = ui.echart({
                'animation': False,
                'tooltip': {'trigger': 'axis'},
                'grid': {'left': 50, 'right': 20, 'top': 30, 'bottom': 40},
                'xAxis': {'type': 'time'},
                'yAxis': {'type': 'value', 'min': V_MIN, 'max': V_MAX, 'name': 'V'},
                'series': [{
                    'type': 'line',
                    'showSymbol': False,
                    'data': points,
                }],
            }).classes('w-full h-96')

    last_seq = seq

    def refresh() -> None:
        nonlocal last_seq
        cur_seq, cur_latest, cur_points = store.snapshot()
        if cur_seq == last_seq:
            return
        last_seq = cur_seq
        gauge.options['series'][0]['data'] = [{'value': round(cur_latest, 2)}]
        line.options['series'][0]['data'] = cur_points
        gauge.update()
        line.update()

    ui.timer(0.1, refresh)   # 新着があるときだけ描画を更新

ui.run(title='VR Monitor', reload=False)

#
# this code is generated by Claude Sonnet 5.5
#
